drop table "stats";

create table "stats"
(
    "id"                 serial primary key,
    "match"              integer references "match" on delete cascade,
    "player"             integer references "player" on delete cascade default null,
    "map_number"         integer not null                              default 0,
    "kills"              integer not null                              default 0,
    "deaths"             integer not null                              default 0,
    "assists"            integer not null                              default 0,
    "flash_assists"      integer not null                              default 0,
    "team_kills"         integer not null                              default 0,
    "suicides"           integer not null                              default 0,
    "damage"             integer not null                              default 0,
    "utility_damage"     integer not null                              default 0,
    "enemies_flashed"    integer not null                              default 0,
    "friendlies_flashed" integer not null                              default 0,
    "knife_kills"        integer not null                              default 0,
    "headshot_kills"     integer not null                              default 0,
    "rounds_played"      integer not null                              default 0,
    "bomb_defuses"       integer not null                              default 0,
    "bomb_plants"        integer not null                              default 0,
    "1k"                 integer not null                              default 0,
    "2k"                 integer not null                              default 0,
    "3k"                 integer not null                              default 0,
    "4k"                 integer not null                              default 0,
    "5k"                 integer not null                              default 0,
    "1v1"                integer not null                              default 0,
    "1v2"                integer not null                              default 0,
    "1v3"                integer not null                              default 0,
    "1v4"                integer not null                              default 0,
    "1v5"                integer not null                              default 0,
    "first_kills_t"      integer not null                              default 0,
    "first_kills_ct"     integer not null                              default 0,
    "first_deaths_t"     integer not null                              default 0,
    "first_deaths_ct"    integer not null                              default 0,
    "trade_kills"        integer not null                              default 0,
    "kast"               integer not null                              default 0,
    "score"              integer not null                              default 0,
    "mvp"                integer not null                              default 0
);
