start transaction;
drop table if exists "stats";
drop table if exists "server";
drop table if exists "host";
drop table if exists "scheduled_match";
drop table if exists "beo1_vote";
drop table if exists "beo3_vote";
drop table if exists "map";
drop table if exists "match";
drop table if exists "team_assignment";
drop table if exists "food_order";
drop table if exists "food_type";
drop table if exists "article_order";
drop table if exists "article_type";
drop table if exists "player";
drop table if exists "team";
drop table if exists "account";
drop table if exists "config";
commit;